name: testt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0  # ✅ Updated to latest compatible version
  firebase_auth: ^4.17.6  # ✅ Updated to match firebase_core
  cloud_firestore: ^4.17.5 # ✅ Updated to match firebase_core
  geolocator: ^10.1.0  # ✅ Latest stable version for geolocation
  firebase_storage: ^11.7.7  # ✅ Updated Firebase Storage version
  file_picker: ^8.0.3       # ✅ File picker for uploading files
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
