// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz8eVb90oxdbTDNfEZYZ8nuClox5-J3dk',
    appId: '1:87653822885:web:f75426c261b7325558384c',
    messagingSenderId: '87653822885',
    projectId: 'testt-a0da8',
    authDomain: 'testt-a0da8.firebaseapp.com',
    storageBucket: 'testt-a0da8.firebasestorage.app',
    measurementId: 'G-BYKWTV9YXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_R3BgfnAlgprvnY5BGE1ZFnhy5BTDFA',
    appId: '1:87653822885:android:841635df35e15b7858384c',
    messagingSenderId: '87653822885',
    projectId: 'testt-a0da8',
    storageBucket: 'testt-a0da8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFwmSzz0r--ssl9mJw7HS2MHxQVWL-maM',
    appId: '1:87653822885:ios:a72c7b6f2e4abe9658384c',
    messagingSenderId: '87653822885',
    projectId: 'testt-a0da8',
    storageBucket: 'testt-a0da8.firebasestorage.app',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFwmSzz0r--ssl9mJw7HS2MHxQVWL-maM',
    appId: '1:87653822885:ios:a72c7b6f2e4abe9658384c',
    messagingSenderId: '87653822885',
    projectId: 'testt-a0da8',
    storageBucket: 'testt-a0da8.firebasestorage.app',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz8eVb90oxdbTDNfEZYZ8nuClox5-J3dk',
    appId: '1:87653822885:web:8cee063d355a946e58384c',
    messagingSenderId: '87653822885',
    projectId: 'testt-a0da8',
    authDomain: 'testt-a0da8.firebaseapp.com',
    storageBucket: 'testt-a0da8.firebasestorage.app',
    measurementId: 'G-H5867HH4WC',
  );
}
